# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build and test

on:
  push:
    branches: [ "lab3" ]
  pull_request:
    branches: [ "lab3" ]

  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore HRDepartment.Domain/HRDepartment.Domain.UnitTest/HRDepartment.Domain.UnitTest.csproj
    - name: Build main project
      run: dotnet build HRDepartment.Domain/HRDepartment.Domain/HRDepartment.Domain.csproj --no-restore
    - name: Build test project
      run: dotnet build HRDepartment.Domain/HRDepartment.Domain.UnitTest/HRDepartment.Domain.UnitTest.csproj --no-restore
    - name: Test
      run: dotnet test HRDepartment.Domain/HRDepartment.Domain.UnitTest/HRDepartment.Domain.UnitTest.csproj --no-build --verbosity normal
