name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore HRDepartment.Domain.sln
    - name: Build
      run: dotnet build HRDepartment.Domain/HRDepartment.Domain.csproj
    - name: Test
      run: dotnet test HRDepartment.Domain.UnitTest/HRDepartment.Domain.UnitTest.csproj --no-build --verbosity normal
